version bump. corrected readme for env directory move.
c3g/freezeman pull request #26
Opened 2021-04-07 19:28 UTC by UlysseFG

2021-04-08 17:25 UTC, jleblond approved these changes

2021-04-08 19:41 UTC, jleblond requested changes
Preferrably this PR could be split into different ones (the readme and env instructions could already pushed), but the unit tests will require more review

2021-04-13 16:12 UTC, UlysseFG commented on backend/fms_core/tests/test_models.py
> +    def test_missing_volume_used_in_extraction(self):
Nice tests. We could possibly add an identical volume_used test for transfer.

2021-04-13 16:27 UTC, UlysseFG reviewed
This looks good ... i suggested another test but this is sugar coating...

2021-04-13 20:44 UTC, jleblond commented
Sure, Ill do and merge it to QC afterwards. I will then merge QC into master

2021-04-13 20:58 UTC, merged