add action-reducer for samplesTable
c3g/freezeman pull request #603
Opened 2023-06-27 17:00 UTC by nafiz1001

2023-07-11 18:02 UTC, nafiz1001 commented
So for the #587 PR has served me well.

2023-07-12 15:38 UTC, ckostiw requested changes

2023-07-12 18:33 UTC, ckostiw commented
If a sample has no associated individual then the Cohort column shows "Loading..." forever.

![Screen Shot 2023-07-12 at 2 32 21 PM](https://github.com/c3g/freezeman/assets/104078019/fe955718-ffca-4af7-8a19-cde026c3b901)

2023-07-12 18:42 UTC, ckostiw commented
I ran sample QC on some samples but the last protocol still shows "Extraction". Shouldn't it now display "Sample QC" since that was the most recent protocol?
![Screen Shot 2023-07-12 at 2 40 28 PM](https://github.com/c3g/freezeman/assets/104078019/34398c9b-21ed-4a5b-9d4f-70c36bf8e6ec)

![Screen Shot 2023-07-12 at 2 41 12 PM](https://github.com/c3g/freezeman/assets/104078019/c9cce25f-7f9d-4d49-9109-df9ffa590ecb)

2023-07-12 18:54 UTC, ckostiw requested changes
The projects associated samples table is not updated after a template is submitted. I ran Normalization on some samples, which generates new samples, and they did not appear in the projects associated samples table until I refreshed the page.

2023-07-19 18:53 UTC, UlysseFG reviewed
This looks ok on the backend side ... not convinced it hsould go in protocol but nowhere seem that great so might as well go with this.

2023-07-19 20:08 UTC, ckostiw requested changes
Two tiny nitpicks

2023-07-19 20:09 UTC, nafiz1001 commented on frontend/src/components/projects/ProjectsAssociatedSamples.tsx
> +            return <>-</>
Already pushed ;)

2023-07-19 20:12 UTC, nafiz1001 commented on frontend/src/selectors.ts
> +export const selectProjectSamplesTable = (state: RootState) => state.projectSamplesTable as ProjectSamplesTable
i've sorted all of the selectors

2023-07-19 20:15 UTC, ckostiw approved these changes

2023-07-20 19:48 UTC, UlysseFG commented
This works as intended ... We'll revisit using the lab feedback when it comes to the confusion of what "last protocol" means.

2023-07-20 19:48 UTC, UlysseFG approved these changes

2023-07-21 13:00 UTC, merged