Feature #1677:  Taxon definitions Nice to have.
c3g/freezeman pull request #640
Opened 2023-08-17 15:35 UTC by nafiz1001

https://206.12.92.46/issues/1677

2023-08-17 18:48 UTC, ckostiw requested changes
* Did we decide not to display taxon names in italics?
* The table needs to be updated after the user creates a new taxon.
* The `taxons` state should be refreshed as well

2023-08-17 18:49 UTC, ckostiw requested changes

2023-08-17 18:49 UTC, ckostiw commented on frontend/src/components/taxons/TaxonsListContent.tsx
> +import React, { useEffect, useMemo, useState } from 'react'
There are a lot of unused imports that should be cleaned up.

2023-08-17 23:05 UTC, nafiz1001 commented
Oops.

2023-08-18 14:57 UTC, nafiz1001 commented
I'm surprised `taxons` state is not refreshed
```typescript
        if (isAdding) {
            dispatch(
                add({ ...new_taxon })
            )
                .then(() => {
                    navigate('/taxons')
                })
                .then(() => { dispatch(list()) })
		.then(() => { dispatch(TaxonsTableActions.setStale(true)) })
                .catch(err => setFormErrors({ ...err.data }))
        } else {
            dispatch(
                update(taxon.id, { ...new_taxon })
            )
                .then(() => {
                    navigate('/taxons')
                })
                .then(() => { dispatch(list()) })
		.then(() => { dispatch(TaxonsTableActions.setStale(true)) })		
                .catch(err => setFormErrors({ ...err.data }))
        }
```

2023-08-21 15:25 UTC, ckostiw approved these changes

2023-08-21 15:27 UTC, merged