Adding parent container and parent coords in labwork steps
c3g/freezeman pull request #643
Opened 2023-08-31 20:08 UTC by JMarce01

- adding filter keys and defintions for front-end
- adding backend filter strings for sorting and filtering

2023-09-01 18:02 UTC, UlysseFG commented on backend/fms_core/viewsets/_constants.py
> +    **_prefix_keys("sample__container__location__coordinate__", _coordinate_filterset_fields),
coordinate is on container not on location this would get you the parent parent coordinate

2023-09-07 20:52 UTC, UlysseFG commented on frontend/src/components/shared/WorkflowSamplesTable/SampleTableColumns.tsx
> +	[SampleColumnID.PARENT_COORDINATES]: 'sample_next_step__sample__container__location__coordinate__name',
This filter look wrong ... This should be the end of path as sample_next_step. ...sample__container__coordinate__name.

2023-09-07 20:52 UTC, UlysseFG commented on frontend/src/components/shared/WorkflowSamplesTable/SampleTableColumns.tsx
> +	[SampleColumnID.PARENT_COORDINATES]: 'container__location__coordinate__name',
This filter look wrong ... This should be the end of path as sample_next_step. ...container__coordinate__name.

2023-09-12 20:08 UTC, UlysseFG commented on frontend/src/components/samples/SampleTableColumns.tsx
> +		columnID: SampleColumnID.PARENT_CONTAINER,
I think we typically use 2 spaces for indentation on the frontend side to keep the indentation from getting too great.

2023-09-12 20:36 UTC, UlysseFG commented on frontend/src/components/samples/SampleTableColumns.tsx
> +		title: 'Parent Coordinates',
you can use "Parent Coords" to mirror the other column and prevent taking space for nothing.

2023-09-12 20:38 UTC, UlysseFG commented on frontend/src/components/samples/SampleTableColumns.tsx
> +		title: 'Parent Container',
Parent Container is not precise enough (could be name or barcode). We should use "Parent Container Barcode" even if it is too long to our taste.

2023-09-12 20:44 UTC, ckostiw requested changes

2023-09-12 20:44 UTC, ckostiw commented on frontend/src/components/samples/SampleTableColumns.tsx
> +					<WithContainerRenderComponent
If there is no parent container and thus no coordinate then we end up displaying "loading..." forever in the coordinate column.
<img width="1557" alt="Screen Shot 2023-09-12 at 4 40 24 PM" src="https://github.com/c3g/freezeman/assets/104078019/2a05b393-d819-455a-befb-529235120ff6">

2023-09-13 16:52 UTC, ckostiw approved these changes

2023-09-21 16:36 UTC, merged